### ISSUE TITLE
Error: Plugin 0 specified in ".../package.json" provided an invalid property of "Environment"

### ISSUE THREAD

**Issue by sedubois** [graphcool/babel-plugin-react-relay#10]
Hi, and thanks for providing this plugin! 

I tried to use it as follows:
- `npm i --save-dev babel-plugin-react-relay@0.9.2-3 react-relay@0.9.3`
- add `"graphql": { "graphql-js": "./server/backend/schema.js"  }` in `package.json`
- add `"plugins": [ "react-relay" ]` to `package.json` `babel` config

However, I get the error in the title (thrown by `babel-core/lib/transformation/plugin.js:131:13`). I am not super familiar with Babel, am I missing something?

**Comment by schickling** [comment]
Hey @sedubois! I'll look into this right away, would you mind joining [our Slack](https://slack.graph.cool) in order to resolve this? That would help a lot to ask a few questions.

**Comment by schickling** [comment]
I guess this is resolved now.

**Comment by sedubois** [comment]
See here for documented workaround: https://github.com/graphcool/babel-plugin-react-relay/pull/11
