### ISSUE TITLE
Force reload of schema?

### ISSUE THREAD

**Issue by dabfleming** [graphcool/babel-plugin-react-relay#14]
Hi, I apologize if this isn't really the ideal place for this question, I'm primarily a backend dev and a little at sea this deep in the frontend.

I'm working on a GraphQL backend and react/relay frontend app at the same time, and often as I add to the schema on the server, I get something like the following error in the console:

```
Uncaught Error: GraphQL validation error ``Cannot query field "newField" on type "Query".`` in file `.../src/components/App.js`. Try updating your GraphQL schema if an argument/field/type was recently added.
```

The same query works if I run manually in graphiql.

If I ctrl-c and `npm start` again, I still get the same issue. I'm fairly sure this issue has gone away on it's own over time. Is there some way to force a reload or no cache of the schema?

**Comment by schickling** [comment]
That's a really good question @dabfleming. That's exactly what we're going to solve with https://github.com/graphcool/graphql-hot-reload

**Comment by dabfleming** [comment]
@schickling I get a 404, I'm assuming that's still a private project? Sounds like something to look forward to though.

**Comment by schickling** [comment]
Just made it public. We'll soon release a first version of this!

**Comment by dabfleming** [comment]
For the record, if anyone else finds this, clearing the cache in `./node_modules/.cache/` seems to do the trick.

Closing.
