### ISSUE TITLE
Node 7 is broken

### ISSUE THREAD

**Issue by schickling** [graphcool/babel-plugin-react-relay#15]
Since this plugin relies on `deasync` we have to wait until https://github.com/abbr/deasync/issues/73 is fixed.

**Comment by jaydenseric** [comment]
Now that the linked `deasync` issue seems to be fixed, is this package still known to be broken in Node 7?

I am trying to set this up and am getting an error, and want to be sure it is not due to this issue:

```
Uncaught Error: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
```

**Comment by schickling** [comment]
Yes, you're right. The `deasync` issue was fixed and is no longer a problem for this plugin.

Your problem seems to be related to something else. Could you please follow up once you fixed it? Seems like a problem a lot of people are running into. Would love to mention this situation in the readme!
