### ISSUE TITLE
Relay doesn't point request correct endpoint.

### ISSUE THREAD

**Issue by ghost** [graphcool/babel-plugin-react-relay#17]
I am currently trying to get Relay to run for the first time with `babel-plugin-react-relay`.

My [graphQL server](https://github.com/MoeSattler/goalie) is not the client serving one, so it has a different port. 
I set that with:`export GRAPHQL_ENDPOINT=http://localhost:4000/graphql`

For some reason though, relay keeps requesting to it's own URL. (just different port in this case, `http://localhost:3000/graphql`). Which obviously ends up being 404d. 

THOUGH the schema get's fetched from the right place (port 4000).

[client code](https://github.com/MoeSattler/goalie-client/)

**Comment by schickling** [comment]
`babel-plugin-react-relay` just sets the endpoint for the development environment not for the app runtime itself.  You additionally need to setup your Relay app like this:

```js
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('https://api.graph.cool/relay/v1/__PROJECT_ID__')
)
```

See [here](https://facebook.github.io/relay/docs/guides-network-layer.html) for more.
