### ISSUE TITLE
Force refresh?

### ISSUE THREAD

**Issue by nuclearspike** [graphcool/babel-plugin-react-relay#19]
I love this plugin, solved an issue I was having but got me so much more. But it seems that it is not updating anymore. It worked until I added another object to my GraphQL server and tried to reference it.

```
Error: GraphQL validation error ``Cannot query field "viewer" on type "Query".`` in file `/Users/paul/RubymineProjects/Project/src/routes/SearchResults/index.js`. Try updating your GraphQL schema if an argument/field/type was recently added.
```

I've tried restarting my servers but no luck. My IDE properly recognizes the new 'viewer' object as do other GraphiQL tools but when I run my app, it doesn't work. Is there a way to force an update?

**Comment by schickling** [comment]
Have you tried to restart your build tool (I guess you're using `webpack`?)

**Comment by nuclearspike** [comment]
I am using the webpack dev server with a nodejs express front end server
and rails graphql/API server. I'd killed and restarted both just to make
sure.

**Comment by schickling** [comment]
Sorry for this question, but are you sure you're pointing the plugin to the right endpoint as mentioned here? https://github.com/graphcool/graphql-config

**Comment by nuclearspike** [comment]
Yes. It worked the first time I ran it and was fine for awhile. The problem
was that once I made a change to the graph and tried to use the new object,
it won't recognize that change.

**Comment by schickling** [comment]
Is there a example codebase you can share with a hosted GraphQL endpoint?

**Comment by nuclearspike** [comment]
Nevermind... I found the error. It was unrelated but just surfaced as this error.

**Comment by schickling** [comment]
Maybe you want to share the solution. Might be helpful for others?

**Comment by nuclearspike** [comment]
There isn't one I can share. It seems to correct itself eventually but it can sometimes take quite a while before it recognizes the change.

Something to note about this setup is that the graph endpoint is a Rails server and the front end server is node.
