### ISSUE TITLE
RelayQL: Unexpected invocation at runtime

### ISSUE THREAD

**Issue by akre54** [graphcool/babel-plugin-react-relay#2]
I just added this transform to a project, and it works like a charm on my machine, but on my coworker's machine she's getting:

```
Uncaught Invariant Violation: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
```

Any ideas? I'm thinking it might have something to do with [this line](https://github.com/graphcool/babel-plugin-react-relay/blob/afbc58383018443e798b165eda7b23fcd1e88145/src/index.js#L47) and maybe a race condition?

Anything else it may be?

**Comment by schickling** [comment]
Thanks for reporting this issue! Which source type are you using? Are you reading a graphql-js  schema? Which OS is your coworker using?

**Comment by akre54** [comment]
Sorry for the lack of details --

We're using the "schema" sourcetype (`.js`). She and I are both on the same OS (Mac 10.11).

Neither of us get errors when building the project (it gives her the same "Relay schema successfully loaded from ./server/graphql/schema.js" message as I get), but the AST replacement works on my machine, and doesn't on hers. In other words, the plugin silently fails until you try to load the page, when it's clear the node hasn't been replaced as it should be.

The project was working with just babel-relay-plugin previously, but it's enough of a pain in the ass to have to rebuild the schema for every change that this seemed like a good alternative.

My next thought was to blow away the node_modules folders on both of our machines, but wanted to see if there was something else to try to track down first. (Trying to add console.log statements around that `loopWhile` line in index.js complains that `console.log` isn't defined).

**Comment by sorenbs** [comment]
Hi Adam

Definitely a pain to manually rebuild the schema every time. Have been using this approach for a month now and it works really well so far.

I don't think this is a race condition caused by the loopWhile. Would appreciate it if you could try to remove the node_modules folder and install again.

Failing that, could you do a quick check to see if the transform is failing in all files or just some files?

**Comment by akre54** [comment]
Just checked. It's not replacing any of the `Relay.QL` calls.

We removed her node_modules folder and reinstalled, but still nothing.

Again, it's working on my machine and her console shows [the success message](https://github.com/graphcool/babel-plugin-react-relay/blob/afbc58383018443e798b165eda7b23fcd1e88145/src/index.js#L72) (which I also see on my machine) so I find this rather odd.

**Comment by schickling** [comment]
Sorry for not getting back earlier. We've just updated the plugin to use the newest version of the relay source. Could you maybe try again and tell us if the problem still occurs?

**Comment by akre54** [comment]
Yup that seems to have fixed it. Thanks for the quick change.

**Comment by sorenbs** [comment]
Glad it worked out!

**Comment by akre54** [comment]
Just upgraded relay to 0.9.0 and GraphQL to 0.6.0 and things broke again (same error message). Can we get a version bump here too?

**Comment by return007** [comment]
I am also getting the same error. Is it still not resolved..?
