### ISSUE TITLE
Can't archive iOS project

### ISSUE THREAD

**Issue by pbassut** [graphcool/babel-plugin-react-relay#20]
When I try to archive a project an uses on my phone it crashes with the error message:
`RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as Relay.QL.`

It works fine on development. But crashes when trying to deploy to the appStore

We currently have an app that's crashing on the appStore because of this.

Please help :(

**Comment by pbassut** [comment]
It works fine on Android, by the way.

**Comment by marktani** [comment]
It sounds like somehow your babel compiler is not being run for the iOS build. Is this maybe about a dev/production configuration?

**Comment by pbassut** [comment]
I didn't setup any dev/production schemes. They're all the same. 
I think the problem seems to be in: https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L93-L107

**Comment by pbassut** [comment]
And by the same I mean, untouched.
This is preventing me from deploying my app. Really annoying bug :(

**Comment by pbassut** [comment]
Argh. 
This was how my `.babelrc` was:
```
{
  "presets": ["react-native"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source", "react-relay"]
    },
  },
}
```

This way it would run react-relay only on development. Meaning that, when archiving the scheme is set to Release, thus no plugins would run. Then I changed it to:

```
{
  "presets": ["react-native"],
  "plugins": ["react-relay"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source", "react-relay"]
    },
  },
}
```

It works now.

**Comment by marktani** [comment]
Awesome you found that :+1: What's your app on the iOS Store?

**Comment by pbassut** [comment]
@marktani It's this one: https://itunes.apple.com/br/app/lavapp/id1242599264?l=en&mt=8
