### ISSUE TITLE
Migrate to Relay Modern & new graphql-config standard

### ISSUE THREAD

**Issue by schickling** [graphcool/babel-plugin-react-relay#21]
With the new standard of [graphql-config](https://github.com/graphcool/graphql-config) and Relay Modern, this plugin should be updated as well.

**Comment by schickling** [comment]
Given the new `relay-compiler` setup this babel plugin is no longer necessary.

**Comment by tim-field** [comment]
What about people sticking with Relay Classic?  This package doesn't appear to work at all now with graphql-cli which is a shame.
