### ISSUE TITLE
Breaking change introducing graphql-config

### ISSUE THREAD

**Issue by schickling** [graphcool/babel-plugin-react-relay#5]
We recently switched over to the [graphql-config](https://github.com/graphcool/graphql-config) configuration format. This unfortunately also means that this plugin no longer supports the `graphql-js` source type.

**Comment by akre54** [comment]
This broke our build. In the future can you guys please make breaking changes only on major version bumps? 

Also, what does it mean that it no longer supports graphql-js type? This changes our build process substantially and was one of the main reasons for using this project in the first place.

**Comment by schickling** [comment]
I totally get your point. The reason why we chose to not upgrade to a new major version is that we want to keep the same versioning as Relay. Apologies for any inconveniences!

**Comment by akre54** [comment]
Maybe the Relay version should be after the patch version then? Seems like they're on two release schedules. New relay versions could either be a major or minor version depending on how breaking the relay version.

Yet another reason to be frustrated at Semver ;)

**Comment by sedubois** [comment]
Does this problem of `graphql-js` config not being supported still apply? It is valid according to your doc: https://github.com/graphcool/graphql-config/tree/a45f164dddae1dc05451b7830c083848ccb706ad#use-local-schema-file-graphqljs

**Comment by akre54** [comment]
Nope, it was fixed in https://github.com/graphcool/graphql-config/pull/4
