### ISSUE TITLE
Intermittent failures during build

### ISSUE THREAD

**Issue by ekosz** [graphcool/babel-plugin-react-relay#6]
Hey there,

We recently switched to `babel-plugin-react-relay` from checking in the schema.json file manually. And during local development this works great. But since switching our CI service has been failing intermittently with this error:

```
ModuleBuildError: Module build failed: TypeError: Cannot read property 'data' of undefined
    at exports.default (/home/ubuntu/dazzle/node_modules/babel-plugin-react-relay/lib/index.js:8:13)
```

It looks like the plugin is not halting before babel wants to know information about the schema. Rebuilding normally doesn't fix the issue. We need to rebuild without a cache (npm install from scratch, etc) is the only thing that seems to fix it. Is this a known issue? If so is there a known work around? 

Thanks!

Here's our version info:

```
Node: 6.5
babel-plugin-react-relay: 0.9.2-3
```

**Comment by schickling** [comment]
Hey @ekosz. That sounds interesting. Unfortunately I haven't seen this issue before, so I'm not aware of a workaround. I'm currently traveling but maybe you'd want to take a look into it yourself? I'd be happy to merge a PR which fixes this.

Please keep in mind that this package is built on top of [graphql-config](https://github.com/graphcool/graphql-config)

**Comment by ekosz** [comment]
Hey @schickling I have a theory about the issue. It looks like this library is using babel to compile from es6 -> es5. Here's the generated code which is currently on npm:

``` js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (babel) {
  if (schema.data) {
    return (0, _babelRelayPlugin2.default)(schema.data)(babel);
  } else {
    return {
      visitor: {}
    };
  }
};

var _babelRelayPlugin = require('babel-relay-plugin');

var _babelRelayPlugin2 = _interopRequireDefault(_babelRelayPlugin);

var _graphqlConfigParser = require('graphql-config-parser');

var _deasync = require('deasync');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var config = (0, _graphqlConfigParser.parse)();

var wait = true;
var schema = void 0,
    error = void 0;

(0, _graphqlConfigParser.resolveSchema)(config).then(function (result) {
  schema = result;
  wait = false;
}).catch(function (err) {
  error = err;
  wait = false;
});

// TODO find a cleaner way to do this
(0, _deasync.loopWhile)(function () {
  return wait;
});

if (error) {
  throw error;
}
```

You'll notice that `exports.default = function (babel) {` is at the top of the file, while in `src` it's at the bottom. Could it be that because of that the function is exported before the code has time to `deasync` loop?

**Comment by schickling** [comment]
Hmm possibly but it would be very weird if using babel turns out to be the problem. Could be a configuration problem though. Is there a way for you to test your idea?

**Comment by schickling** [comment]
Thanks @cahnory for fixing this! 👍
