### ISSUE TITLE
babel-relay-plugin not pinned down

### ISSUE THREAD

**Issue by sedubois** [graphcool/babel-plugin-react-relay#9]
Hi and thanks for providing this plugin! I'm trying to use it and naturally thought it should go with `babel-relay-plugin@0.9.2`, as its version is `0.9.2-3` 😉 However, `package.json` actually specifies `babel-relay-plugin@^0.9.2` and will therefore currently download `0.9.3`. I suggest to either pin down the exact `babel-relay-plugin` version in `package.json`, or switch to an independent version scheme.

**Comment by schickling** [comment]
Oh that's a very good point! I'll fix this right away!

**Comment by schickling** [comment]
I've published two new versions on NPM:
- `0.9.2-4` which corresponds to babel-relay-plugin `0.9.2`
- `0.9.3` which corresponds to babel-relay-plugin `0.9.3`
